### ISSUE TITLE
Nested wildcards are not working

### ISSUE THREAD

**Issue by josejulio** [namshi/mockserver#51]
I'm trying to mock the following call:

GET api/namespaces/my-namespace/services/my-service/metrics

I tried the following file:
`api/namespaces/__/services/__/metrics/GET.mock` and is not working, the server answers: "Not Mocked"

However this works: `api/namespaces/__/services/my-service/metrics/GET.mock` 

It makes me believe that nesting the wilcards is not working (or not yet implemented).

**Comment by christianrondeau** [comment]
It's indeed not supported. I just hit the same issue, and the code in `getWildcardPath` actually "tries" all combinations of paths that contain a single `__`... so anything with more than one variable won't work.

I'll try and submit a PR.

**Comment by odino** [comment]
This should be fixed in `v2.2.0` thanks to @christianrondeau :)
