### ISSUE TITLE
CORS support?

### ISSUE THREAD

**Issue by KhanhHH** [namshi/mockserver#52]
I can't send request from my app which is running on localhost port 4200 to mock server (port 8080), is there any solution? Thanks!

**Comment by odino** [comment]
Hi @KhanhHH, I think we haven't thought of mockserver in the context of a browser (where you'd bump into issues with CORS). Can you try adding the [ACAO](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header to your responses? That might fix it.

**Comment by asgoth** [comment]
Hello @KhanhHH, it might be that you need an OPTIONS call first. Check https://github.com/namshi/mockserver/issues/46#issuecomment-418832787

**Comment by Hollister009** [comment]
@odino `Access-Control-Allow-Origin: *` resolved my issue, thanks

**Comment by huyanhp** [comment]
I personally prefer disabling CORS check of Chrome ( about 30 secs of search and trial) , even though I managed to setup CORS for our integration server with nginx.

**Comment by james2doyle** [comment]
I used an OPTIONS.mock file to support `window.fetch` calls in the browser. 

You can see the details here: https://gist.github.com/james2doyle/a9caf383a5c6ac66594a5831adeddb00
