### ISSUE TITLE
ReferenceError: Atomics is not defined

### ISSUE THREAD

**Issue by vishwasjois** [namshi/mockserver#66]
Failure on node 8.9.4

Stacktrace ; 
project-dir\node_modules\mockserver\mockserver.js:381
        Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, delay);
        ^
ReferenceError: Atomics is not defined

**Comment by odino** [comment]
Atomics were introduced in node 8.10 -- try an upgrade :)

**Comment by NiQDeveloper** [comment]
> Atomics were introduced in node 8.10 -- try an upgrade :)

Then update the package.json file to indicate that the engine required is "node": ">= 8.10" - not ">=6.0".

**Comment by odino** [comment]
Hey @NiQDeveloper, thanks for flagging this! We've just updated the package (with `3.0.1`) and also flagged the right version of the engine for this to work. Feel free to open a PR next time, would be glad to review anything coming in :smile:
