### ISSUE TITLE
Multiple headers with the same name are not supported

### ISSUE THREAD

**Issue by Auxx** [namshi/mockserver#75]
HTTP allows for multiple headers to be sent with the same name, for example:

```
Access-Control-Expose-Headers: accept
Access-Control-Expose-Headers: authorization
Access-Control-Expose-Headers: content-type
Access-Control-Expose-Headers: content-length
Access-Control-Expose-Headers: origin
Access-Control-Expose-Headers: tr-client
Access-Control-Expose-Headers: tr-admin
Access-Control-Expose-Headers: dnt
Access-Control-Expose-Headers: Content-Disposition
```

Such response can not be reproduced by mockserver. I suggest that headers should be represented as an array of name and value pairs, not a map.

**Comment by odino** [comment]
Makes sense -- happy to review a PR if anyone's interested in implementing this.

**Comment by ijavid** [comment]
Same here, Set-Cookie headers should work also.
